spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://svc-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}

        - id: menu-items
          uri: lb://svc-menu-commandes
          predicates:
            - Path=/api/menu/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: commandes
          uri: lb://svc-menu-commandes
          predicates:
            - Path=/api/commandes/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: cuisine
          uri: lb://svc-cuisine
          predicates:
            - Path=/api/cuisine/**
          filters:
            - RewritePath=/api/cuisine/(?<segment>.*), /$\{segment}

        - id: inventaire
          uri: lb://svc-inventaire-prevision
          predicates:
            - Path=/api/inventaire/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: prevision
          uri: lb://svc-inventaire-prevision
          predicates:
            - Path=/api/prevision/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: rh
          uri: lb://svc-rh-planning
          predicates:
            - Path=/api/rh/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: planning
          uri: lb://svc-rh-planning
          predicates:
            - Path=/api/planning/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: notifications
          uri: lb://svc-notifications-reporting
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: reporting
          uri: lb://svc-notifications-reporting
          predicates:
            - Path=/api/reporting/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
