server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false

      routes:
        - id: auth-service
          uri: lb://SVC-AUTH
          predicates:
            - Path=/api/auth/**

        - id: menu-commandes-service
          uri: lb://SVC-MENU-COMMANDES
          predicates:
            - Path=/api/menu/**,/api/commandes/**

        - id: cuisine-service
          uri: lb://SVC-CUISINE
          predicates:
            - Path=/api/cuisine/**

        - id: inventaire-service
          uri: lb://SVC-INVENTAIRE
          predicates:
            - Path=/api/inventaire/**

        - id: rh-service
          uri: lb://SVC-RH
          predicates:
            - Path=/api/rh/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
